# Generated by Django 5.2.11 on 2026-03-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Spanish', 'Spanish'), ('French', 'French'), ('Other', 'Other')], db_index=True, default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['language', 'id'], name='movies_movi_languag_eff690_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-rating', 'id'], name='movies_movi_rating_682c6e_idx'),
        ),
    ]
