# Generated by Django 5.2.11 on 2026-03-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_genre_movie_language_alter_movie_name_movie_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Gujarati', 'Gujarati'), ('Marathi', 'Marathi'), ('Other', 'Other')], db_index=True, default='English', max_length=20),
        ),
    ]
